# https://circleci.com/docs/2.0/

version: 2

workflows:
  version: 2
  build_release:
    jobs:
      - mdl
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: golang:1.12
    working_directory: /go/src/github.com/percolate/retry
    steps:
      - checkout
      - run: go vet ./...
      - run:
          shell: /bin/bash
          name: go fmt
          command: |
            ! gofmt -l $(find . -path ./vendor -prune -o  -type f -name '*.go' -print) 2>&1 | read
      - run: make test
      - run: sbin/codecov

  mdl:
    docker:
      - image: rsrchboy/mdl
    steps:
      - checkout
      - run:
          name: Validate Markdown
          command: |
            mdl $(find . -path ./vendor -prune -o -type f -name '*.md' -print)

  release:
    docker:
      - image: 667005031541.dkr.ecr.us-west-1.amazonaws.com/circleci/cci-release:2.1.0
    steps:
      - checkout
      - deploy:
          name: Deploy to GitHub Releases
          command: |
            ci-make-release $(cat VERSION.txt)
